/*
Deployment script for StackOverflow2010

This code was generated by a tool.
Changes to this file may cause incorrect behavior and will be lost if
the code is regenerated.
*/

GO
SET ANSI_NULLS, ANSI_PADDING, ANSI_WARNINGS, ARITHABORT, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER ON;

SET NUMERIC_ROUNDABORT OFF;


GO
:setvar DatabaseName "StackOverflow2010"
:setvar DefaultFilePrefix "StackOverflow2010"
:setvar DefaultDataPath "C:\SqlData\MSSQL13.MSSQLSERVER\MSSQL\DATA\"
:setvar DefaultLogPath "C:\SqlData\MSSQL13.MSSQLSERVER\MSSQL\DATA\"

GO
:on error exit
GO
/*
Detect SQLCMD mode and disable script execution if SQLCMD mode is not supported.
To re-enable the script after enabling SQLCMD mode, execute the following:
SET NOEXEC OFF; 
*/
:setvar __IsSqlCmdEnabled "True"
GO
IF N'$(__IsSqlCmdEnabled)' NOT LIKE N'True'
    BEGIN
        PRINT N'SQLCMD mode must be enabled to successfully execute this script.';
        SET NOEXEC ON;
    END


GO
USE [$(DatabaseName)];


GO
PRINT N'Rename refactoring operation with key  is skipped, element [dbo].[Votes].[column_1] (SqlSimpleColumn) will not be renamed to LegacyId';


GO

IF (SELECT OBJECT_ID('tempdb..#tmpErrors')) IS NOT NULL DROP TABLE #tmpErrors
GO
CREATE TABLE #tmpErrors (Error int)
GO
SET XACT_ABORT ON
GO
SET TRANSACTION ISOLATION LEVEL READ COMMITTED
GO
BEGIN TRANSACTION
GO
/*
The column [dbo].[Votes].[LegacyId] on table [dbo].[Votes] must be added, but the column has no default value and does not allow NULL values. If the table contains data, the ALTER script will not work. To avoid this issue you must either: add a default value to the column, mark it as allowing NULL values, or enable the generation of smart-defaults as a deployment option.

The type for column Id in table [dbo].[Votes] is currently  VARCHAR (100) NOT NULL but is being changed to  INT IDENTITY (1, 1) NOT NULL. Data loss could occur and deployment may fail if the column contains data that is incompatible with type  INT IDENTITY (1, 1) NOT NULL.
*/
GO
PRINT N'Starting rebuilding table [dbo].[Votes]...';


GO
BEGIN TRANSACTION;

SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;

SET XACT_ABORT ON;

CREATE TABLE [dbo].[tmp_ms_xx_Votes] (
    [Id]           INT           IDENTITY (1, 1) NOT NULL,
    [PostId]       INT           NOT NULL,
    [UserId]       INT           NULL,
    [BountyAmount] INT           NULL,
    [VoteTypeId]   INT           NOT NULL,
    [CreationDate] DATETIME      NOT NULL,
    [LegacyId]     VARCHAR (100) NOT NULL,
    CONSTRAINT [tmp_ms_xx_constraint_PK_Votes__Id1] PRIMARY KEY CLUSTERED ([Id] ASC)
);

IF EXISTS (SELECT TOP 1 1 
           FROM   [dbo].[Votes])
    BEGIN
        --SET IDENTITY_INSERT [dbo].[tmp_ms_xx_Votes] ON;
        INSERT INTO [dbo].[tmp_ms_xx_Votes] ( [PostId], [UserId], [BountyAmount], [VoteTypeId], [CreationDate],[LegacyId])
        SELECT   --[Id],
                 [PostId],
                 [UserId],
                 [BountyAmount],
                 [VoteTypeId],
                 [CreationDate]
				 ,Id
        FROM     [dbo].[Votes]
        --ORDER BY [Id] ASC;
        --SET IDENTITY_INSERT [dbo].[tmp_ms_xx_Votes] OFF;
    END

DROP TABLE [dbo].[Votes];

EXECUTE sp_rename N'[dbo].[tmp_ms_xx_Votes]', N'Votes';

EXECUTE sp_rename N'[dbo].[tmp_ms_xx_constraint_PK_Votes__Id1]', N'PK_Votes__Id', N'OBJECT';

COMMIT TRANSACTION;

SET TRANSACTION ISOLATION LEVEL READ COMMITTED;


GO
IF @@ERROR <> 0
   AND @@TRANCOUNT > 0
    BEGIN
        ROLLBACK;
    END

IF OBJECT_ID(N'tempdb..#tmpErrors') IS NULL
    CREATE TABLE [#tmpErrors] (
        Error INT
    );

IF @@TRANCOUNT = 0
    BEGIN
        INSERT  INTO #tmpErrors (Error)
        VALUES                 (1);
        BEGIN TRANSACTION;
    END


GO

IF EXISTS (SELECT * FROM #tmpErrors) ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT>0 BEGIN
PRINT N'The transacted portion of the database update succeeded.'
COMMIT TRANSACTION
END
ELSE PRINT N'The transacted portion of the database update failed.'
GO
IF (SELECT OBJECT_ID('tempdb..#tmpErrors')) IS NOT NULL DROP TABLE #tmpErrors
GO
GO
PRINT N'Update complete.';


GO
